services:
  ghost:
    image: ghost:latest
    restart: always
    ports:
      - "2368:2368"
    environment:
      - url=https://aosn.de  
      - NODE_ENV=production
      - database__client=mysql
      - database__connection__host=db
      - database__connection__user=root
      - database__connection__password=your_password
      - database__connection__database=ghost
    depends_on:
      - db
    volumes:
      - ./ghost-content:/var/lib/ghost/content

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: your_password
      MYSQL_DATABASE: ghost
    volumes:
      - ./mysql-data:/var/lib/mysql

volumes:
  ghost:
  db:
