name: conduwuit
services:
  homeserver:
#        image: girlbossceo/conduwuit:latest
    image: ghcr.io/girlbossceo/conduwuit:main-haswell
    container_name: conduwuit
    network_mode: "host"
    restart: unless-stopped
    ports:
      - 6167:6167
      - 8446:8446
    volumes:
      - ./conduwuit_db:/var/lib/conduwuit
      - ./conduwuit.toml:/etc/conduwuit.toml
#      - ./resolv.conf:/etc/resolv.conf:ro
    environment:
      CONDUWUIT_SERVER_NAME: con.aosn.de # EDIT THIS
      CONDUWUIT_DATABASE_PATH: /var/lib/conduwuit
      CONDUWUIT_PORT: 6167
      CONDUWUIT_MAX_REQUEST_SIZE: 20000000 # in bytes, ~20 MB
      CONDUWUIT_ALLOW_REGISTRATION: 'true'
      CONDUWUIT_REGISTRATION_TOKEN: '天王盖地虎' # A registration token is required when registration is allowed.
      #CONDUWUIT_YES_I_AM_VERY_VERY_SURE_I_WANT_AN_OPEN_REGISTRATION_SERVER_PRONE_TO_ABUSE: 'true'
      CONDUWUIT_ALLOW_FEDERATION: 'true'
      CONDUWUIT_ALLOW_CHECK_FOR_UPDATES: 'true'
      CONDUWUIT_TRUSTED_SERVERS: '["matrix.org"]'
      #CONDUWUIT_LOG: warn,state_res=warn
      CONDUWUIT_ADDRESS: 0.0.0.0
      CONDUWUIT_CONFIG: '/etc/conduwuit.toml' # Uncomment if you mapped config toml above
