[global]
database_path = "/var/lib/conduwuit"
database_backend = "rocksdb"
port = 6167
address = "127.0.0.1"
max_request_size = 200_000_000
zstd_compression = true
gzip_compression = false
brotli_compression = false
allow_guest_registration = false
log_guest_registrations = false
allow_guests_auto_join_rooms = false
allow_registration = true
allow_federation = true
allow_room_creation = true
allow_public_room_directory_over_federation = false
allow_public_room_directory_without_auth = false
lockdown_public_room_directory = true
allow_device_name_federation = false
url_preview_max_spider_size = 384_000
url_preview_check_root_domain = false
federation_idle_per_host = 3
allow_profile_lookup_federation_requests = true
log = "debug"
log_colors = true
cache_capacity_modifier = 4.0
db_cache_capacity_mb = 4096.0
rocksdb_direct_io = true
rocksdb_log_level = "error"
rocksdb_max_log_file_size = 10485760
rocksdb_log_time_to_roll = 0
rocksdb_parallelism_threads = 0
rocksdb_compaction_ioprio_idle = true
rocksdb_compaction_prio_idle = false
rocksdb_max_log_files = 5
rocksdb_compression_algo = "zstd"
rocksdb_compression_level = 3
rocksdb_bottommost_compression_level = 3
rocksdb_bottommost_compression = true
rocksdb_stats_level = 1
rocksdb_repair = false
rocksdb_recovery_mode = 1
query_over_tcp_only = true
ip_lookup_strategy = 5
request_conn_timeout = 30
request_timeout = 30
request_total_timeout = 120
request_idle_timeout = 15
request_idle_per_host = 10
well_known_conn_timeout = 10
well_known_timeout = 10
federation_timeout = 300
federation_idle_timeout = 60
sender_timeout = 60
sender_idle_timeout = 60
sender_retry_backoff_limit = 3600
appservice_timeout = 20
appservice_idle_timeout = 60
pusher_idle_timeout = 30
allow_local_presence = true
allow_incoming_presence = true
allow_outgoing_presence = true
presence_timeout_remote_users = true
presence_idle_timeout_s = 120
presence_offline_timeout_s = 900
allow_incoming_read_receipts = true
allow_outgoing_read_receipts = true
allow_outgoing_typing = true
allow_incoming_typing = true
typing_federation_timeout_s = 15
typing_client_timeout_max_s = 30
turn_allow_guests = true

[global.well_known]
server = "mc.aosn.de:443"
client = "https://mc.aosn.de"